//
//  Request.swift
//  Fetch
//
//  Created by David Hardiman on 13/02/2016.
//  Copyright © 2016 David Hardiman. All rights reserved.
//

import Foundation

/**
 *  Simple protocol representing a network request
 */
public protocol Request {

    /// The URL to fetch
    var url: URL { get }
    
    /// The HTTP method to use
    var method: HTTPMethod { get }

    /// The headers for the request
    var headers: [String: String]? { get }

    /// The body of the request
    var body: Data? { get }
    
    /// Allows customisation to the underlying `URLRequest` generated by the `Request`.
    /// The proposed `URLRequest` is passed into the method based on the `Request`s configuration.
    ///
    /// - Parameter urlRequest: The proposed `URLRequest`
    /// - Returns: The `URLRequest` that should be made.
    ///
    /// - Note: A default implementation is provided for this function which simply returns the
    /// proposed request.
    func urlRequest(for urlRequest: URLRequest) -> URLRequest
}

public extension Request {
    func urlRequest(for urlRequest: URLRequest) -> URLRequest {
        urlRequest
    }
}
