version: 2
jobs:
  iOStest:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Run Tests
          command: |
              xcodebuild -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -sdk iphonesimulator -scheme "Fetch-iOS" clean test |
              tee xcodebuild.log |
              xcpretty --report html --output test_output/results.html --report junit --output test_output/unit-tests/results.xml
      - run:
          name: Post Coverage
          command: bundle exec slather
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output/results.html
      - store_artifacts:
          path: xcodebuild.log
  tvOStest:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
              xcodebuild -destination 'platform=tvOS Simulator,name=Apple TV,OS=latest' -sdk appletvsimulator -scheme "Fetch-tvOS" clean test |
              tee xcodebuild.log
  macOStest:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
              xcodebuild -scheme "Fetch-macOS" clean test |
              tee xcodebuild.log
      - store_artifacts:
          path: xcodebuild.log
workflows:
  version: 2
  run-tests:
    jobs:
      - iOStest
      - tvOStest
      - macOStest

