name: Test

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.configurations.destination }}
    runs-on: macos-15
    strategy:
      matrix:
        configurations:
          - destination: "platform=macOS"
            scheme: "Fetch-macOS"
            platform: "macOS"
          - destination: "platform=iOS Simulator,name=iPhone 15 Pro"
            scheme: "Fetch-iOS"
            platform: "iOS"
          - destination: "platform=tvOS Simulator,name=Apple TV"
            scheme: "Fetch-tvOS"
            platform: "tvOS"
    
    steps:
    - name: Xcode Select
      run: sudo xcode-select -s /Applications/Xcode_16.2.app

    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests on ${{ matrix.configurations.destination }}
      run: xcodebuild -destination "${{ matrix.configurations.destination }}" -scheme "${{ matrix.configurations.scheme }}" test
